community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final-pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
    path('professional/', include('professional.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie-update', views.movie_update, name="movie_update"),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('recommended', views.recommended, name='recommended'),
]

professional/urls.py
from django.urls import path
from . import views

app_name = 'professional'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:proreview_pk>/', views.detail, name='detail'),
    path('<int:proreview_pk>/delete/', views.delete, name='delete'),
    path('<int:proreview_pk>/update/', views.update, name='update'),
    path('<int:proreview_pk>/like/', views.like, name='like'),
]

community/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from movies.models import Movie

class Review(models.Model):
    title = models.CharField(max_length=100)
    rank = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/models.py
from django.db import models
import datetime

class Movie(models.Model):
    title = models.CharField(max_length=100)
    movie_id = models.IntegerField()
    release_date = models.DateField(blank=True)
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.TextField()

movies/forms.py
from django import forms

# Create your forms here.

movies/views.py
import requests
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.conf import settings
from .models import Movie


# Create your views here.
def movie_update(request):
    if settings.IS_FIRST:
        for i in range(1, 4):
            # data 받아오기
            my_url = f'https://api.themoviedb.org/3/movie/popular?api_key=fae9dc8695dc36b190fa7f4146fc979f&page={i}'
            response = requests.get(my_url)
            movie_dict = response.json()
            movie_list = movie_dict.get('results')
            for movie in movie_list:
                movie_id = movie.get('id')
                # 기존 DB에 있는 영화의 경우
                if Movie.objects.filter(movie_id=movie_id).exists():
                    continue
                # 새로운 영화일 경우 DB에 새로 저장
                else:
                    title = movie.get('original_title')
                    movie_id = movie.get('id')
                    overview = movie.get('overview')
                    if movie.get('release_date'):
                        release_date = movie.get('release_date')
                    else:
                        release_date = '2999-01-01'
                    poster_path = movie.get('poster_path')
                    popularity = movie.get('popularity')
                    vote_count = movie.get('vote_count')
                    vote_average = movie.get('vote_average')
                    genre_ids = movie.get('genre_ids')

                    # Movie DB에 저장하기
                    Movie.objects.create(title=title, overview=overview, release_date=release_date, poster_path=poster_path, popularity=popularity, vote_count=vote_count, vote_average=vote_average, genres=genre_ids, movie_id=movie_id)
        settings.IS_FIRST = False
    return redirect('movies:index')

@require_GET
def index(request):
    if settings.IS_FIRST:
        return redirect('movies:movie_update')
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


@require_GET
def detail(request, movie_id):
    movie = get_object_or_404(Movie, movie_id=movie_id)
    genre_dict = {
        28: 'Action',
        12: 'Adventure',
        16: 'Animation',
        35: 'Comedy',
        80: 'Crime',
        99: 'Documentary',
        18: 'Drama',
        10751: 'Family',
        14: 'Fantasy',
        36: 'History',
        27: 'Horror',
        10402: 'Music',
        9648: 'Mystery',
        10749: 'Romance',
        878: 'Science Fiction',
        10770: 'TV Movie',
        53: 'Thriller',
        10752: 'War',
        37: 'Western',
    }
    genre_ids = list(map(int, movie.genres[1:-1].split(', ')))
    genres = []
    for genre in genre_ids:
        genres.append(genre_dict.get(genre))

    # 장르 추천기능
    genre_search = ','.join(map(str, genre_ids))
    my_url = f'https://api.themoviedb.org/3/discover/movie?with_genres={genre_search}&api_key=fae9dc8695dc36b190fa7f4146fc979f'
    response = requests.get(my_url)
    recommend_dict = response.json()
    recommend_list = recommend_dict.get('results')[:18]
    for recommend in recommend_list:
        # 기존 DB에 있는 영화의 경우
        movie_id = recommend.get('id')
        if Movie.objects.filter(movie_id=movie_id).exists():
            continue
        # 새로운 영화일 경우 DB에 새로 저장
        else:
            title = recommend.get('original_title')
            overview = recommend.get('overview')
            if recommend.get('release_date'):
                release_date = recommend.get('release_date')
            else:
                release_date = '2999-01-01'
            poster_path = recommend.get('poster_path')
            popularity = recommend.get('popularity')
            vote_count = recommend.get('vote_count')
            vote_average = recommend.get('vote_average')
            genre_ids = recommend.get('genre_ids')

            Movie.objects.create(title=title, overview=overview, release_date=release_date, poster_path=poster_path, popularity=popularity, vote_count=vote_count, vote_average=vote_average, genres=genre_ids, movie_id=movie_id)

    # 그 영화의 리뷰 목록 표시
    reviews = movie.review_set.order_by('-pk')[:10]

    context = {
        'movie': movie,
        'genres': genres,
        'reviews': reviews,
        'recommend_list': recommend_list,
    }
    return render(request, 'movies/detail.html', context)


@require_GET
def recommended(request):

    return render(request, 'movies/recommended.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="w-100" alt="poster img">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 id="genres" data-genres="{{ movie.genres }}" class="card-title kotitle">{{ movie.title }}</h3>
        <p class="card-text">Release Date : {{ movie.release_date|date:'Y. m. d' }}</p>
        <p class="card-text">Genres : {% for genre in genres %}{% if forloop.last %}{{ genre }} {% else %}{{ genre }}, {% endif %}{% endfor %}</p>
        <p class="card-text">{{ movie.overview }}</p>
        <p class="card-text">Popularity : {{ movie.popularity }}</p>
        <p class="card-text">Vote Average : {{ movie.vote_average }}</p>
        <a href="{% url 'community:create' movie.movie_id %}"><button class="btn btn-outline-secondary">[리뷰 작성하러 가기]</button></a>
        {% if user.user_rank == 4 %}
          <a href="{% url 'professional:create' movie.movie_id %}"><button class="btn btn-outline-secondary">[Pro 리뷰 작성하러 가기]</button></a>
        {% endif %}
        <hr>
        <h4 class="mb-3">최신 리뷰 목록</h4>
        <ul class="list-group">
          {% for review in reviews %}
            <a href="{% url 'community:detail' review.pk %}" class="list-group-item">{{ review.title }} [{{ review.comment_set.all|length }}]</a>
          {% endfor %}
        </ul>
        
      </div>
    </div>
  </div>
  </div>
  <hr>
  
  {% comment %} 장르 추천기능 {% endcomment %}
  <h3>Recommendations by Genres</h3>
  <br>
  <div id="recGenre" class="row row-cols-2 row-cols-md-4 row-cols-lg-6 g-4">
  {% for recommend in recommend_list %}
    <a href="{% url 'movies:detail' recommend.id %}">
      <div class="col">
        <div class="card">
          <img src="https://image.tmdb.org/t/p/w500/{{ recommend.poster_path }}" class="card-img-top" alt="poster img" style="height: 246px;">
          <div class="card-body" style="height: 95px; padding-top: 7px;">
            <p class="card-title" style="font-size: 14px;">{{ recommend.title }}</p>
          </div>
        </div>
      </div>
    </a>
  {% endfor %}
  </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
  <header style="background-color: #cfd4da; height: 280px;">
    <div class="col-md-6 ms-5 px-0">
      <h1 class="pt-4 display-4 fst-italic entitle">Rethink what a Review can do</h1>
      <p class="lead my-3 fst-italic">If you want to get ahead, Write a review and Acquire a stamp</p>
    </div>
  </header>
{% endblock  %}
{% block content %}
  <div class="d-flex justify-content-end">
  </div>
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
  {% for movie in movies %}
    <div class="col">
      <a href="{% url 'movies:detail' movie.movie_id %}">
        <div class="card">
          <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path}}" class="card-img-top" alt="poster img" style="height: 388.5px;">
          <div class="card-body" style="height: 192px;">
            <h5 class="card-title kotitle">{{ movie.title }}</h5>
            <p class="card-text">Release Date: {{ movie.release_date|date:'Y. m. d' }}</p>
            <p class="card-text">Vote Avg: {{ movie.vote_average }}</p>
          </div>        
        </div>
      </a>
    </div>
  {% endfor %}
{% endblock %}
{% block footer %}
  <footer style="background-color: #cfd4da; height: 130px;">
    <div class="container text-center">
      <div class="row">
        <div class="col mt-3">
          <img src="{% static 'joy_image.png' %}" alt="logo" class="w-25">
          <p class="mt-2 text-secondary">Final Project by Team Joy</p>
        </div>
        <div class="col mt-3">
          <a href="https://www.themoviedb.org/"><p class="text-secondary mt-4 mb-1">Movie Information from TMDB API</p></a>
          <a href="https://www.flaticon.com/"><p class="text-secondary">Stamp images from Flaticon</p></a>
        </div>
        <div class="col mt-3">
          <p class="text-secondary mt-4 mb-1">Developed: 2021.5.28.</p>
          <p class="text-secondary">SSAFY 5th Seoul_4 </p>
        </div>
      </div>
    </div>
  </footer>
{% endblock  %}

movies/templates/movies/popup.html
<h1>POPUP!!</h1>