accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final-pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
    path('professional/', include('professional.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie-update', views.movie_update, name="movie_update"),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('recommended', views.recommended, name='recommended'),
]

community/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from movies.models import Movie

class Review(models.Model):
    title = models.CharField(max_length=100)
    rank = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['title', 'rank', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import JsonResponse, HttpResponse
from .models import Review, Comment
from movies.models import Movie
from accounts.models import Stamp
from .forms import ReviewForm, CommentForm


@require_GET
def index(request):
    if request.user.is_authenticated:
        reviews = Review.objects.order_by('-pk')
        context = {
            'reviews': reviews,
        }
        return render(request, 'community/index.html', context)
    return redirect('accounts:login')


@login_required
@require_http_methods(['GET', 'POST'])
def create(request, movie_id):
    movie = get_object_or_404(Movie, movie_id=movie_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST) 
        stamp = get_object_or_404(Stamp, user=request.user)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.movie = movie
            review.save()
            
            # 등업 확인하기
            if request.user.user_rank == 1:
                if len(request.user.review_set.all()) >= 10 and len(request.user.comment_set.all()) >= 10:
                    request.user.user_rank = 2
                    request.user.save()
                    stamp.bonus = True
                    stamp.counter += 1
                    stamp.save()
                return redirect('community:detail', review.pk)
            else:
                if len(request.user.review_set.all()) >= 30:
                    stamp.review_stamp = True
                    stamp.counter += 1
                    stamp.save()

                # 장르 스탬프 확인하기
                genre_ids = list(map(int, movie.genres[1:-1].split(', ')))
                for genre in genre_ids:
                    if genre == 28:
                        if not stamp.action:
                            stamp.action = True
                            stamp.counter += 1
                            continue
                    elif genre == 12:
                        if not stamp.adventure:
                            stamp.adventure = True
                            stamp.counter += 1
                            continue
                    elif genre == 16:
                        if not stamp.animation:
                            stamp.animation = True
                            stamp.counter += 1
                            continue
                    elif genre == 35:
                        if not stamp.comedy:
                            stamp.comedy = True
                            stamp.counter += 1
                            continue
                    elif genre == 80:
                        if not stamp.crime:
                            stamp.crime = True
                            stamp.counter += 1
                            continue
                    elif genre == 99:
                        if not stamp.documentary:
                            stamp.documentary = True
                            stamp.counter += 1
                            continue
                    elif genre == 18:
                        if not stamp.drama:
                            stamp.drama = True
                            stamp.counter += 1
                            continue
                    elif genre == 10751:
                        if not stamp.family:
                            stamp.family = True
                            stamp.counter += 1
                            continue
                    elif genre == 14:
                        if not stamp.fantasy:
                            stamp.fantasy = True
                            stamp.counter += 1
                            continue
                    elif genre == 36:
                        if not stamp.history:
                            stamp.history = True
                            stamp.counter += 1
                            continue
                    elif genre == 27:
                        if not stamp.horror:
                            stamp.horror = True
                            stamp.counter += 1
                            continue
                    elif genre == 10402:
                        if not stamp.music:
                            stamp.music = True
                            stamp.counter += 1
                            continue
                    elif genre == 9648:
                        if not stamp.mystery:
                            stamp.mystery = True
                            stamp.counter += 1
                            continue
                    elif genre == 10749:
                        if not stamp.romance:
                            stamp.romance = True
                            stamp.counter += 1
                            continue
                    elif genre == 878:
                        if not stamp.science_fiction:
                            stamp.science_fiction = True
                            stamp.counter += 1
                            continue
                    elif genre == 10770:
                        if not stamp.tv_movie:
                            stamp.tv_movie = True
                            stamp.counter += 1
                            continue
                    elif genre == 53:
                        if not stamp.thriller:
                            stamp.thriller = True
                            stamp.counter += 1
                            continue
                    elif genre == 10752:
                        if not stamp.war:
                            stamp.war = True
                            stamp.counter += 1
                            continue
                    elif genre == 37:
                        if not stamp.western:
                            stamp.western = True
                            stamp.counter += 1
                            continue
                stamp.save()
            
            # 3단계 등업 조건 확인
            if stamp.counter >= 15 and request.user.user_rank == 2:
                request.user.user_rank = 3
                request.user.save()
            elif stamp.counter == 24:
                stamp.all_stamp = True
                stamp.counter += 1
                stamp.save()
            return redirect('community:detail', review.pk)

    else:
        form = ReviewForm()
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'community/create.html', context)


@require_POST
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect('community:index')
    return redirect('accounts:login')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('movies:index')
        # return HttpResponseForbidden()
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'community/update.html', context)


@require_GET
def detail(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comments = review.comment_set.all()
        comment_form = CommentForm()
        context = {
            'review': review,
            'comment_form': comment_form,
            'comments': comments,
        }
        return render(request, 'community/detail.html', context)
    return redirect('accounts:login')


@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        # 등업 확인하기
        if request.user.user_rank == 1:
            if len(request.user.review_set.all()) >= 10 and len(request.user.comment_set.all()) >= 10:
                request.user.user_rank = 2
                request.user.save()
        # 스탬프 확인하기
        stamp = get_object_or_404(Stamp, user=request.user)
        if len(request.user.comment_set.all()) >= 30:
            stamp.comment_stamp = True
            stamp.counter += 1
            stamp.save()

        if stamp.counter == 15 and request.user.user_rank == 2:
            request.user.user_rank = 3
            request.user.save()
        elif stamp.counter == 24:
            stamp.all_stamp = True
            stamp.counter += 1
            stamp.save()
        return redirect('community:detail', review.pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)


@require_POST
def delete_comment(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        # return HttpResponseForbidden()
    return redirect('community:detail', review_pk)
    # return HttpResponse(status=401)


@login_required
@require_http_methods(['GET', 'POST'])
def update_comment(request, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':

community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="text-center entitle">CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-outline-primary btn-sm">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.movie_id %}">[back]</a>
{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
  <h2 class="text-center entitle">DETAIL</h2>
  <h3 class="kotitle">{{ review.title }}</h3>
  <p>작성자: {{ review.user }}</p>
  <p class="d-flex justify-content-end" style="font-size: 13px;">작성 시각: {{ review.created_at }}</p>
  <hr>
  <h5>영화: <a class="" href="{% url 'movies:detail' review.movie.movie_id %}">{{ review.movie.title }}</a></h5>
  <p>평점: {{ review.rank }}</p>
  <p>{{ review.content|linebreaks }}</p>
  <br>
  {% if request.user == review.user %}
    <a href="{% url 'community:update' review.pk %}"><button class="btn btn-outline-primary btn-sm">Update</button></a> 
    <form action="{% url 'community:delete' review.pk %}" method="POST" style="display: inline;">
      {% csrf_token %}
      <button class="btn btn-outline-danger btn-sm">Delete</button>
    </form>
  {% endif %}
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
      <span>{{ comment.user }} - {{ comment.content }}</span>
      {% if request.user == comment.user %}
        <form action="{% url 'community:delete_comment' review.pk comment.pk %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <button class="btn btn-outline-danger btn-sm">Delete</button>
        </form>
      {% endif %}
    </div>
  {% empty %}
    <p>No comments yet</p>
  {% endfor %}
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <button class="btn btn-outline-primary btn-sm">Submit</button>
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a href="{% url 'community:index' %}">[back]</a>

{% endblock  %}

community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="entitle fst-italic">Community</h1>
  <hr>
  <table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Title</th>
      <th scope="col">Movie</th>
      <th scope="col">User</th>
      <th scope="col">Date</th>
      <th scope="col">Likes</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <th scope="row">{{ review.pk }}</th>
      <td><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a> [{{ review.comment_set.all|length }}]</td>
      <td><a href="{% url 'movies:detail' review.movie.movie_id %}">{{ review.movie.title }}</a></td>
      <td><a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></td>
      <td><p>{{ review.created_at|date:'Y. m. d' }}</p></td>
      <td><p id="like-count-{{ review.pk }}">{{ review.like_users.all|length }}</p></td></td>
      <td>
        <form class="d-inline like-form" data-review-id="{{ review.pk }}">
          {% csrf_token %}
          {% if user in review.like_users.all %}
            <button class="btn btn-link">
              <i class="fas fa-heart fa-lg" style="color:crimson;" id="like-{{ review.pk }}"></i>
            </button>
          {% else %}
            <button class="btn btn-link">
              <i class="fas fa-heart fa-lg" style="color:black;" id="like-{{ review.pk }}"></i>
            </button>
          {% endif %}
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  </table>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    // csrf
    const forms = document.querySelectorAll('.like-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    
    // like
    forms.forEach((form) => {
      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const reviewId = event.target.dataset.reviewId

        axios({
          method: 'post',
          url: `http://127.0.0.1:8000/community/${reviewId}/like/`,
          headers: {'X-CSRFToken': csrftoken},
        })
          .then((response) => {
            console.log(response)
            const count = response.data.count
            const liked = response.data.liked

            const likeHeart = document.querySelector(`#like-${reviewId}`)
            likeHeart.style = liked ? 'color:crimson;' : 'color:black;'

            console.log(count)
            const likeCount = document.querySelector(`#like-count-${reviewId}`)
            likeCount.innerText = count

          })
          .catch((error) => {
            if (error.response.status === 401) {
              window.location.href = '/accounts/login/'
            }
        })
      })
    })
  </script>
{% endblock %}

community/templates/community/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="text-center entitle">UPDATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-outline-primary btn-sm">Submit</button>
  </form>
  <hr>
  <a href="{% url 'community:detail' review.pk %}">[back]</a>
{% endblock %}