accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final-pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
    path('professional/', include('professional.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie-update', views.movie_update, name="movie_update"),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('recommended', views.recommended, name='recommended'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followers = models.ManyToManyField('self', symmetrical=False, related_name='followings', blank=True)
    user_rank = models.IntegerField(default=1)


class Stamp(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    counter = models.IntegerField(default=0)

    # 기본 1개
    bonus = models.BooleanField(default=False)
    # 장르 19개
    action = models.BooleanField(default=False)
    adventure = models.BooleanField(default=False)
    animation = models.BooleanField(default=False)
    comedy = models.BooleanField(default=False)
    crime = models.BooleanField(default=False)
    documentary = models.BooleanField(default=False)
    drama = models.BooleanField(default=False)
    family = models.BooleanField(default=False)
    fantasy = models.BooleanField(default=False)
    history = models.BooleanField(default=False)
    horror = models.BooleanField(default=False)
    music = models.BooleanField(default=False)
    mystery = models.BooleanField(default=False)
    romance = models.BooleanField(default=False)
    science_fiction = models.BooleanField(default=False)
    tv_movie = models.BooleanField(default=False)
    thriller = models.BooleanField(default=False)
    war = models.BooleanField(default=False)
    western = models.BooleanField(default=False)
    # 추가 5개
    review_stamp = models.BooleanField(default=False)
    comment_stamp = models.BooleanField(default=False)
    follower_stamp = models.BooleanField(default=False)
    joined_stamp = models.BooleanField(default=False)
    all_stamp = models.BooleanField(default=False)

community/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from movies.models import Movie

class Review(models.Model):
    title = models.CharField(max_length=100)
    rank = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.http import HttpResponse, JsonResponse
import datetime
from pytz import timezone, utc
from .models import Stamp
from .forms import CustomUserCreationForm


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            # 스탬프 생성
            Stamp.objects.create(user=request.user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            
            # 스탬프 - 가입 후 경과 날짜 확인
            time1 = request.user.date_joined # not naive
            time2 = datetime.datetime.now(tz=datetime.timezone.utc)
            if (time2-time1).days > 7:
                stamp = get_object_or_404(Stamp, user=request.user)
                stamp.joined_stamp = True
                stamp.counter += 1
                stamp.save()
                if stamp.counter == 15 and request.user.user_rank == 2:
                    request.user.user_rank = 3
                    request.user.save()
                elif stamp.counter == 24:
                    stamp.all_stamp = True
                    stamp.counter += 1
                    stamp.save()
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')


@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    stamp = get_object_or_404(Stamp, user=person)
    # follower 스탬프 확인
    if len(person.followers.all()) >= 1:
        stamp.follower_stamp = True
        stamp.counter += 1
        stamp.save()
        if stamp.counter == 15 and request.user.user_rank == 2:
            request.user.user_rank = 3
            request.user.save()
        elif stamp.counter == 24:
            stamp.all_stamp = True
            stamp.counter += 1
            stamp.save()

    context = {
        'person': person,
        'stamp': stamp,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                followed = False
            else:
                person.followers.add(user)
                followed = True
            context = {
                'followed': followed,
                'followers': person.followers.count(),
                'followings': person.followings.count(),
            }
            return JsonResponse(context)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/_follow.html
<br>
<h1 class="display-4">{{ person.username }}</h1>
{% with followings=person.followings.all followers=person.followers.all %}
  <p>User Rank: {{ person.user_rank }}</p>
  <p class="lead">
    Following : 
    <span id="followings-count">{{ followings|length }}</span>
    / Followers : 
    <span id="followers-count">{{ followers|length }}</span>
  </p>
  <!-- 팔로우 버튼 -->
  {% if request.user != person %}
    <form class="follow-form" data-person-id="{{ person.pk }}">
      {% csrf_token %}
      {% if request.user in followers %}
        <button class="btn" id="follow-btn" style="background-color: #d5e6bd;">Unfollow</button>
      {% else %}
        <button class="btn" id="follow-btn" style="background-color: #d5e6bd;">Follow</button>
      {% endif %}
    </form>
  {% endif %}
{% endwith %}
<hr>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const form = document.querySelector('.follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  form.addEventListener('submit', function (event) {
    event.preventDefault()
    const personId = event.target.dataset.personId

    axios({
      method: 'post',
      url: `http://127.0.0.1:8000/accounts/follow/${personId}/`,
      headers: {'X-CSRFToken': csrftoken},
    })

      .then((response) => {
        const followed = response.data.followed
        const followers = response.data.followers
        const followings = response.data.followings

        const followBtn = document.querySelector('#follow-btn')
        followBtn.innerText = followed ? 'Unfollow' : 'Follow'
        // 색상변화 추가 필요
      
        const followingsCount = document.querySelector('#followings-count')
        followingsCount.innerText = followings
        const followersCount = document.querySelector('#followers-count')
        followersCount.innerText = followers
      })
  })
</script>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'accounts/_follow.html' %}
<div class="row">
  <section class="col" style="float: left;">
    <h3>Reviews [{{ person.review_set.all|length }}]</h3>
    <ul class="list-group">
      {% for review in person.review_set.all %}
        <a class="list-group-item" href="{% url 'community:detail' review.pk %}">{{ review.title }}</a>
      {% endfor %}
    </ul>
    <hr>

    <h3>Comments [{{ person.comment_set.all|length }}]</h3>
    <ul class="list-group">
      {% for comment in person.comment_set.all %}
        <a class="list-group-item" href="{% url 'community:detail' comment.review.pk %}">{{ comment.content }}</a>
      {% endfor %}
    </ul>
    <hr>

    <h3>Likes</h3>
    <ul class="list-group">
      {% for review in person.like_reviews.all %}
        <a class="list-group-item" href="{% url 'community:detail' review.pk %}">{{ review.title }}</a>
      {% endfor %}
    </ul>
    <hr>

    <a href="{% url 'community:index' %}">[back]</a>
  </section>

  <aside class="col ms-4" style="float: right;">
    <h2 id="get-stamp" data-my-stamp="{{ stamp }}">Stamp Zone</h2>
    {% if person.user_rank < 2 %}
      <h4 class="kotitle">2등급 이상 회원에게 오픈됩니다.</h4>
      <p>리뷰 10개, 댓글 10개 이상 작성 시 2등급 회원이 되어 스탬프를 사용할 수 있습니다.</p>
    {% else %}
      <p>총 스탬프: {{ stamp.counter }}개</p>
      <table class="table table-bordered text-center" style="font-size: 13px; display: block;">
      <thead>
        <tr>
          <th scope="col" style="width: 104px;">
            {% if stamp.action %}
              <img src="{% static 'action2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'action.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Action
          </th>
          <th scope="col" style="width: 104px;">
            {% if stamp.adventure %}
              <img src="{% static 'adventure2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'adventure.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Adventure
          </th>
          <th scope="col" style="width: 104px;">
            {% if stamp.animation %}
              <img src="{% static 'animation2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'animation.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Animation
          </th>
          <th scope="col" style="width: 104px;">
            {% if stamp.comedy %}
              <img src="{% static 'comedy2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'comedy.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Comedy
          </th>
          <th scope="col" style="width: 104px;">
            {% if stamp.crime %}
              <img src="{% static 'crime2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'crime.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Crime
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">
            {% if stamp.documentary %}
              <img src="{% static 'documentary2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'documentary.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Documentary
          </th>
          <td>
            {% if stamp.drama %}
              <img src="{% static 'drama2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'drama.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Drama
          </td>
          <td>
            {% if stamp.family %}
              <img src="{% static 'family2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'family.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Family
          </td>
          <td>
            {% if stamp.fantasy %}
              <img src="{% static 'fantasy2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'fantasy.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Fantasy
          </td>
          <td>
            {% if stamp.history %}
              <img src="{% static 'history2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'history.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>History
          </td>
        </tr>
        <tr>
          <th scope="row">
            {% if stamp.horror %}
              <img src="{% static 'horror2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'horror.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Horror
          </th>
          <td>
            {% if stamp.music %}
              <img src="{% static 'music2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'music.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Music
          </td>
          <td>
            <img src="{% static 'bonus.png' %}" alt="" style="height: 50px; width: 50px;">
            <br>Bonus
          </td>
          <td>
            {% if stamp.mystery %}
              <img src="{% static 'mystery2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'mystery.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Mystery
          </td>
          <td>
            {% if stamp.romance %}
              <img src="{% static 'romance2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'romance.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Romance
          </td>
        </tr>
        <tr>
          <th scope="row">
            {% if stamp.science_fiction %}
              <img src="{% static 'sf2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'sf.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>SF
          </th>
          <td>
            {% if stamp.tv_movie %}
              <img src="{% static 'tvmovie2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'tvmovie.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>TV Movie
          </td>
          <td>
            {% if stamp.thriller %}
              <img src="{% static 'thriller2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'thriller.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Thriller
          </td>
          <td>
            {% if stamp.war %}
              <img src="{% static 'war2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'war.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>War
          </td>
          <td>
            {% if stamp.western %}
              <img src="{% static 'western2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'western.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Western
          </td>
        </tr>
        <tr>
          <th scope="row">
            {% if stamp.review_stamp %}
              <img src="{% static 'review2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'review.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Review
          </th>
          <td>
            {% if stamp.comment_stamp %}
              <img src="{% static 'comment2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'comment.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Comments
          </td>
          <td>
            {% if stamp.follower_stamp %}
              <img src="{% static 'follower2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'follower.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Followers
          </td>
          <td>
            {% if stamp.joined_stamp %}
              <img src="{% static 'joined2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'joined.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Joined
          </td>
          <td>
            {% if stamp.all_stamp %}
              <img src="{% static 'all2.png' %}" alt="" style="height: 50px; width: 50px;">
            {% else %}
              <img src="{% static 'all.png' %}" alt="" style="height: 50px; width: 50px;">
            {% endif %}
            <br>Total 24
          </td>
        </tr>
      </tbody>
      </table>
    {% endif %}
    
    <div>
      <hr>
      <h4 class="kotitle">스탬프 안내사항</h4>
      <p style="margin-bottom: 5px;">2등급 달성 시 bonus 스탬프를 획득합니다.</p>
      <p style="margin-bottom: 5px;">장르 스탬프는 해당 장르의 영화 리뷰 작성 시 획득할 수 있습니다.</p>
      <p style="margin-bottom: 5px;">리뷰, 댓글 스탬프는 각 30개 이상 작성 시 획득할 수 있습니다.</p>
      <p style="margin-bottom: 5px;">팔로워 스탬프는 팔로워가 30명 이상일 경우 획득할 수 있습니다.</p>
      <p style="margin-bottom: 5px;">가입일자 스탬프는 가입일 이후 경과 일수가 7일 이상일 경우 획득할 수 있습니다.</p>
      <p style="margin-bottom: 5px;">왕관 스탬프는 다른 모든 스탬프를 획득할 경우 얻는 최종 스탬프 입니다.</p>
      <p style="margin-bottom: 5px;">총 15개 이상의 스탬프 획득 시 3등급 회원이 되어 Pro Community를 이용할 수 있습니다.</p>
    </div>
  </aside>
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>
{% endblock  %}