accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final-pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
    path('professional/', include('professional.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie-update', views.movie_update, name="movie_update"),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('recommended', views.recommended, name='recommended'),
]

professional/urls.py
from django.urls import path
from . import views

app_name = 'professional'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/create/', views.create, name='create'),
    path('<int:proreview_pk>/', views.detail, name='detail'),
    path('<int:proreview_pk>/delete/', views.delete, name='delete'),
    path('<int:proreview_pk>/update/', views.update, name='update'),
    path('<int:proreview_pk>/like/', views.like, name='like'),
]

final-pjt/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #cfd4da;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'movies:index' %}"><img src="{% static 'joy_image.png' %}" style="height: 50px;" alt="brand img"></a>
    <a class="nav-link active ahover" aria-current="page" href="{% url 'movies:index' %}">Home</a>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link ahover" href="{% url 'community:index' %}">Community</a>
        </li>
          {% if request.user.user_rank < 3 %}
            <!-- Button trigger modal -->
            <li class="nav-item">
              <button type="button" class="btn btn-link nav-link" data-bs-toggle="modal" data-bs-target="#proModal">
                Pro-Community
              </button>
              <!-- Modal -->
              <div class="modal fade" id="proModal" tabindex="-1" aria-labelledby="proModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="proModalLabel">등급제한</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <p>3등급 이상만 이용 가능한 게시판입니다!</p>
                      <p>3등급 회원이 되기 위해서는 스탬프 15개 이상이 필요합니다.</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <a href="{% url 'accounts:profile' user.username %}"><button type="button" class="btn" style="background-color: #d5e6bd;">스탬프 확인하러 가기</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link ahover" href="{% url 'professional:index' %}">Pro-Community</a>
            </li>
          {% endif %}
      </ul>
      <ul class="navbar-nav d-flex">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link ahover" href="{% url 'accounts:profile' request.user.username %}">Hello, {{ request.user.username }}</a>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-link nav-link" data-bs-toggle="modal" data-bs-target="#stampModal">
              Membership: {{ user.user_rank }}
            </button>
            <!-- Modal -->
            <div class="modal fade" id="stampModal" tabindex="-1" aria-labelledby="stampModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="stampModalLabel">스탬프를 모아보세요!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body text-center">
                  <figure class="figure">
                    <img src="{% static 'stamp_img.png' %}" alt="stamp" class="w-75">
                    <figcaption class="figure-caption mt-3">등급 2를 달성하시면 스탬프를 찍을 수 있습니다.</figcaption>
                    <figcaption class="figure-caption">스탬프를 모아 Pro-Community를 즐겨보세요!</figcaption>
                  </figure>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {% if request.user.is_authenticated %}
                      <a href="{% url 'accounts:profile' user.username %}"><button type="button" class="btn" style="background-color: #d5e6bd;">스탬프 확인하러 가기</button></a>
                    {% else %}
                      <a href="{% url 'accounts:signup' %}"><button type="button" class="btn" style="background-color: #d5e6bd;">가입하러 가기</button></a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="nav-link btn btn-link">Logout</button>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link ahover" href="{% url 'accounts:signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link ahover" href="{% url 'accounts:login' %}">Login</a>
          </li> 
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

final-pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/earlyaccess/kopubbatang.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/dacf7dcd9c.js" crossorigin="anonymous"></script>
  <title>pjt-joy</title>
  <style>
    body {
      font-family: 'Noto Serif KR', serif;
      background-color: #f8f9fb;
    }
    .entitle {
      font-family: 'Playfair Display', serif;
    }
    .kotitle {
      font-family: 'Nanum Myeongjo', serif;
      {% comment %} font-family: 'KoPub Batang', serif; {% endcomment %}
    }
    a {
      text-decoration: none;
      color: black;
    }
  </style>
</head>
<body>
  {% include '_navbar.html' %}
  {% block header %}
  {% endblock  %}
  <section class="container my-3">
    {% block content %}
    {% endblock %}
  </section>
  {% block footer %}
  {% endblock  %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>